global:
  scrape_interval:     2s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8080']
        labels:
          application: 'Product Service Application'